[dev-frontend]
alias = "df"
description = "starts the frontend in dev mode"
cmd = "yarn dev"

[build-frontend]
alias = "bf"
description = "generates fresh ts client and builds the frontend"
cmd = "yarn build"
after = "gen-client"