name: Pytest

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        working-directory: client/core/py/
        run: |
          python -m pip install --upgrade pip
          pip install -r test_requirements.txt

      - name: Run tests
        working-directory: client/core/py/
        run: |
          pytest